#!/usr/bin/env python3
"""Generate src/Bristles.inl from res/Duster_bristles.svg.

For each <line> in a bristles-* group, emits a BristleDef record:
  - anchor   = endpoint with the larger y (where the bristle meets the handle)
  - rest tip = endpoint with the smaller y (top of the bristle)
  - width    = the group's stroke-width
  - r,g,b,a  = the group's stroke colour + opacity, as floats in [0,1]
"""

import os
import xml.etree.ElementTree as ET

SVG_NS = "http://www.w3.org/2000/svg"
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "res", "Duster_bristles.svg")
OUT = os.path.join(REPO, "src", "Bristles.inl")

BRISTLE_GROUP_IDS = ["bristles-back", "bristles-main", "bristles-highlight"]


def hex_to_rgb(s):
    s = s.lstrip("#")
    return (
        int(s[0:2], 16) / 255.0,
        int(s[2:4], 16) / 255.0,
        int(s[4:6], 16) / 255.0,
    )


def find_group(root, gid):
    for g in root.iter(f"{{{SVG_NS}}}g"):
        if g.get("id") == gid:
            return g
    raise RuntimeError(f"Missing group id={gid!r} in {SRC}")


def main():
    tree = ET.parse(SRC)
    root = tree.getroot()
    rows = []
    for gid in BRISTLE_GROUP_IDS:
        g = find_group(root, gid)
        r, gc, b = hex_to_rgb(g.get("stroke", "#000000"))
        a = float(g.get("opacity", "1.0"))
        width = float(g.get("stroke-width", "0.3"))
        for line in g.findall(f"{{{SVG_NS}}}line"):
            x1, y1 = float(line.get("x1")), float(line.get("y1"))
            x2, y2 = float(line.get("x2")), float(line.get("y2"))
            (tx, ty), (ax, ay) = ((x1, y1), (x2, y2)) if y1 < y2 else ((x2, y2), (x1, y1))
            rows.append((gid, ax, ay, tx, ty, width, r, gc, b, a))

    out = [
        "// Auto-generated by tools/gen_bristle_data.py. Do not edit by hand.",
        "// Source: res/Duster_bristles.svg",
        "",
        "static const BristleDef kBristles[] = {",
    ]
    last_gid = None
    for gid, ax, ay, tx, ty, w, r, gc, b, a in rows:
        if gid != last_gid:
            out.append(f"\t// {gid}")
            last_gid = gid
        out.append(
            f"\t{{ {ax:.3f}f, {ay:.3f}f, {tx:.3f}f, {ty:.3f}f, "
            f"{w:.3f}f, {r:.4f}f, {gc:.4f}f, {b:.4f}f, {a:.4f}f }},"
        )
    out.append("};")
    out.append(
        "static constexpr int kNumBristles = "
        "sizeof(kBristles) / sizeof(kBristles[0]);"
    )
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(OUT, REPO)} ({len(rows)} bristles)")


if __name__ == "__main__":
    main()
